name: Deploy

on: 
  push:
    branches: 
      - master
    

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Build
      run: |
        npm install && npm run build

    - name: Deploy
      uses: easingthemes/ssh-deploy@v2.1.2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SOURCE: "dist/"
        REMOTE_HOST: "118.190.211.5"
        REMOTE_USER: "root"
        TARGET: "/app/project/travel/build/"
